apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-web
  template:
    metadata:
      labels:
        app: ms-web
    spec:
      containers:
        - name: ms-web
          image: nginx:alpine
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
