apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: httpproxy
  labels:
    app: demo-app
    tier: ingress
spec:
  virtualhost:
    fqdn: anything.com
  routes:
    - conditions:
        - prefix: /web
      pathRewritePolicy:
        replacePrefix:
          - prefix: /web
            replacement: /
      services:
        - name: ms-web
          port: 80
    - conditions:
        - prefix: /api
      services:
        - name: ms-api
          port: 80
